name: Xcode - Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and test the project
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test
        env:
          SCHEME: CI
          PROJECT: EssentialFeed.xcodeproj
        run: |
          filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          xcodebuild clean build test -project "$PROJECT" -scheme "$SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
